package actividad_1_1_c.Interfaces;

import actividad_1_1_c.ClasesEInterfaces.Vehiculo;
import java.util.ArrayList;

public class AlquilerDeVehiculos extends javax.swing.JFrame {

    ArrayList<Vehiculo> listaDeVehiculos;

    public AlquilerDeVehiculos(ArrayList<Vehiculo> lista) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaDeVehiculos = lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alquilerDeVehiclosJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        alquilerDeVehiculosJMenuBar = new javax.swing.JMenuBar();
        listarJMenu = new javax.swing.JMenu();
        alquilarJMenu = new javax.swing.JMenu();
        alquilarTurismoJMenuItem = new javax.swing.JMenuItem();
        alquilarCamionJMenuitem = new javax.swing.JMenuItem();
        devolverJMenu = new javax.swing.JMenu();
        salirJMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alquiler de vehIculos");
        setMinimumSize(new java.awt.Dimension(550, 400));
        setResizable(false);

        alquilerDeVehiclosJPanel.setMaximumSize(new java.awt.Dimension(550, 400));
        alquilerDeVehiclosJPanel.setMinimumSize(new java.awt.Dimension(550, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("ALQUILER DE VEHICULOS");

        javax.swing.GroupLayout alquilerDeVehiclosJPanelLayout = new javax.swing.GroupLayout(alquilerDeVehiclosJPanel);
        alquilerDeVehiclosJPanel.setLayout(alquilerDeVehiclosJPanelLayout);
        alquilerDeVehiclosJPanelLayout.setHorizontalGroup(
            alquilerDeVehiclosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alquilerDeVehiclosJPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        alquilerDeVehiclosJPanelLayout.setVerticalGroup(
            alquilerDeVehiclosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alquilerDeVehiclosJPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        listarJMenu.setText("LISTAR");
        listarJMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarJMenuMouseClicked(evt);
            }
        });
        alquilerDeVehiculosJMenuBar.add(listarJMenu);

        alquilarJMenu.setText("ALQUILAR");

        alquilarTurismoJMenuItem.setText("Alquilar turismo");
        alquilarTurismoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alquilarTurismoJMenuItemActionPerformed(evt);
            }
        });
        alquilarJMenu.add(alquilarTurismoJMenuItem);

        alquilarCamionJMenuitem.setText("Alquilar Camión");
        alquilarCamionJMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alquilarCamionJMenuitemActionPerformed(evt);
            }
        });
        alquilarJMenu.add(alquilarCamionJMenuitem);

        alquilerDeVehiculosJMenuBar.add(alquilarJMenu);

        devolverJMenu.setText("DEVOLVER");
        devolverJMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devolverJMenuMouseClicked(evt);
            }
        });
        alquilerDeVehiculosJMenuBar.add(devolverJMenu);

        salirJMenu.setText("SALIR");
        salirJMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirJMenuMouseClicked(evt);
            }
        });
        alquilerDeVehiculosJMenuBar.add(salirJMenu);

        setJMenuBar(alquilerDeVehiculosJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alquilerDeVehiclosJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alquilerDeVehiclosJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirJMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirJMenuMouseClicked

        this.dispose();

    }//GEN-LAST:event_salirJMenuMouseClicked

    private void listarJMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarJMenuMouseClicked

        VentanaListar nuevaVentanaListar = new VentanaListar(this.listaDeVehiculos);
        nuevaVentanaListar.setVisible(true);

    }//GEN-LAST:event_listarJMenuMouseClicked

    private void alquilarTurismoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alquilarTurismoJMenuItemActionPerformed

        AlquilerDeCoches nuevoAlquilerDeCoches = new AlquilerDeCoches(this.listaDeVehiculos);
        nuevoAlquilerDeCoches.setVisible(true);
    }//GEN-LAST:event_alquilarTurismoJMenuItemActionPerformed

    private void alquilarCamionJMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alquilarCamionJMenuitemActionPerformed

        AlquilerDeCamiones nuevaAlquilerDeCamiones = new AlquilerDeCamiones(this.listaDeVehiculos);
        nuevaAlquilerDeCamiones.setVisible(true);

    }//GEN-LAST:event_alquilarCamionJMenuitemActionPerformed

    private void devolverJMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolverJMenuMouseClicked

        DevolverVehiclos nuevoDevolverVehiclos = new DevolverVehiclos(this.listaDeVehiculos);
        nuevoDevolverVehiclos.setVisible(true);

    }//GEN-LAST:event_devolverJMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alquilarCamionJMenuitem;
    private javax.swing.JMenu alquilarJMenu;
    private javax.swing.JMenuItem alquilarTurismoJMenuItem;
    private javax.swing.JPanel alquilerDeVehiclosJPanel;
    private javax.swing.JMenuBar alquilerDeVehiculosJMenuBar;
    private javax.swing.JMenu devolverJMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu listarJMenu;
    private javax.swing.JMenu salirJMenu;
    // End of variables declaration//GEN-END:variables
}
