package actividad_1_1_c.Interfaces;

import actividad_1_1_c.ClasesEInterfaces.Camion;
import actividad_1_1_c.ClasesEInterfaces.Turismo;
import actividad_1_1_c.ClasesEInterfaces.Vehiculo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AlquilerDeCamiones extends javax.swing.JFrame {

    ArrayList<Vehiculo> listaDeVehiculos;

    public AlquilerDeCamiones(ArrayList<Vehiculo> lista) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaDeVehiculos = lista;
        diasDeAlquilerCamionesJPanel.setVisible(false);
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alquilerDeCamionesJPanel = new javax.swing.JPanel();
        alquilerDeCamionesJLabel = new javax.swing.JLabel();
        indicarMatriculaJPanel = new javax.swing.JPanel();
        indicarMatriculaCamionJLabel = new javax.swing.JLabel();
        matriculaDeCamionJTextField = new javax.swing.JTextField();
        continuarMatriculaJButton = new javax.swing.JButton();
        diasDeAlquilerCamionesJPanel = new javax.swing.JPanel();
        indicarNumeroDeDiasJLabel = new javax.swing.JLabel();
        numeroDeDiasAlquilerJTextField = new javax.swing.JTextField();
        continuarNumeroDeDiasJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alquiler de camiones");
        setMinimumSize(null);
        setResizable(false);

        alquilerDeCamionesJPanel.setMaximumSize(null);
        alquilerDeCamionesJPanel.setName(""); // NOI18N

        alquilerDeCamionesJLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        alquilerDeCamionesJLabel.setText("ALQUILER DE CAMIONES");

        indicarMatriculaJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        indicarMatriculaJPanel.setMaximumSize(null);
        indicarMatriculaJPanel.setPreferredSize(new java.awt.Dimension(488, 124));

        indicarMatriculaCamionJLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        indicarMatriculaCamionJLabel.setText("INDICAR LA MATRÍCULA DEL CAMIÓN CONTRATADO:");

        continuarMatriculaJButton.setText("CONTINUAR");
        continuarMatriculaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarMatriculaJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indicarMatriculaJPanelLayout = new javax.swing.GroupLayout(indicarMatriculaJPanel);
        indicarMatriculaJPanel.setLayout(indicarMatriculaJPanelLayout);
        indicarMatriculaJPanelLayout.setHorizontalGroup(
            indicarMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indicarMatriculaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(indicarMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indicarMatriculaCamionJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, indicarMatriculaJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(continuarMatriculaJButton))
                    .addGroup(indicarMatriculaJPanelLayout.createSequentialGroup()
                        .addComponent(matriculaDeCamionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        indicarMatriculaJPanelLayout.setVerticalGroup(
            indicarMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indicarMatriculaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indicarMatriculaCamionJLabel)
                .addGap(18, 18, 18)
                .addComponent(matriculaDeCamionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(continuarMatriculaJButton)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        diasDeAlquilerCamionesJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        diasDeAlquilerCamionesJPanel.setMaximumSize(null);
        diasDeAlquilerCamionesJPanel.setName(""); // NOI18N
        diasDeAlquilerCamionesJPanel.setPreferredSize(new java.awt.Dimension(488, 125));

        indicarNumeroDeDiasJLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        indicarNumeroDeDiasJLabel.setText("INDICAR NÚMERO DE DÍAS DE ALQUILER:");

        continuarNumeroDeDiasJButton.setText("CONTINUAR");
        continuarNumeroDeDiasJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarNumeroDeDiasJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diasDeAlquilerCamionesJPanelLayout = new javax.swing.GroupLayout(diasDeAlquilerCamionesJPanel);
        diasDeAlquilerCamionesJPanel.setLayout(diasDeAlquilerCamionesJPanelLayout);
        diasDeAlquilerCamionesJPanelLayout.setHorizontalGroup(
            diasDeAlquilerCamionesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diasDeAlquilerCamionesJPanelLayout.createSequentialGroup()
                .addGroup(diasDeAlquilerCamionesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diasDeAlquilerCamionesJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(indicarNumeroDeDiasJLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diasDeAlquilerCamionesJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(continuarNumeroDeDiasJButton)))
                .addContainerGap())
            .addGroup(diasDeAlquilerCamionesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeroDeDiasAlquilerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diasDeAlquilerCamionesJPanelLayout.setVerticalGroup(
            diasDeAlquilerCamionesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diasDeAlquilerCamionesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indicarNumeroDeDiasJLabel)
                .addGap(18, 18, 18)
                .addComponent(numeroDeDiasAlquilerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(continuarNumeroDeDiasJButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout alquilerDeCamionesJPanelLayout = new javax.swing.GroupLayout(alquilerDeCamionesJPanel);
        alquilerDeCamionesJPanel.setLayout(alquilerDeCamionesJPanelLayout);
        alquilerDeCamionesJPanelLayout.setHorizontalGroup(
            alquilerDeCamionesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alquilerDeCamionesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alquilerDeCamionesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alquilerDeCamionesJPanelLayout.createSequentialGroup()
                        .addComponent(alquilerDeCamionesJLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(indicarMatriculaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diasDeAlquilerCamionesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        alquilerDeCamionesJPanelLayout.setVerticalGroup(
            alquilerDeCamionesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alquilerDeCamionesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alquilerDeCamionesJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indicarMatriculaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diasDeAlquilerCamionesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alquilerDeCamionesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alquilerDeCamionesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarMatriculaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarMatriculaJButtonActionPerformed

        String matricula = matriculaDeCamionJTextField.getText();
        String numeroDeDias = "";
        String textoDialogo = "[i] Error detectado:\n";

        if (this.listaDeVehiculos.stream().anyMatch(camion -> camion instanceof Turismo
                && camion.getMatricula().equalsIgnoreCase(matricula))) {

            textoDialogo += "Esa matricula no pertenece a un camion";
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR AL ALQUILAR TURISMO", JOptionPane.QUESTION_MESSAGE);

        } else if (this.listaDeVehiculos.stream().anyMatch(
                camion -> camion instanceof Camion
                && camion.isAlquilado()
                && camion.getMatricula().equalsIgnoreCase(matricula))) {

            textoDialogo += "El camion con matrícula \n" + matricula + " ya está alquilado\n";
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR AL ALQUILAR CAMIÓN", JOptionPane.QUESTION_MESSAGE);

        } else if (!matricula.isEmpty()
                && listaDeVehiculos
                        .stream()
                        .anyMatch(
                                camion -> camion.getMatricula().equalsIgnoreCase(matricula))) {

            matriculaDeCamionJTextField.setEditable(false);
            continuarMatriculaJButton.setEnabled(false);
            diasDeAlquilerCamionesJPanel.setVisible(true);

        } else {
            if (matricula.isEmpty()) {

                textoDialogo += "No se ha proporcionado matrícula\n";

            } else if (!matricula.matches("^[A-Za-z]{1,2}-[0-9]{4}-[A-Za-z]{1,3}$")) {

                textoDialogo += "La matricula no tiene el formato correcto, el formato correcto es XX-XXXX-XXX donde:\n"
                        + " - XX:   representa el pais o region de la matrícula\n"
                        + " - XXXX: representa el numero de la matricula\n"
                        + " - XXX:  representa las tres ultimas letras de una matrícula\n"
                        + "XX solo pueden contener letras, XXXX solo pueden contener numeros y XXX solo pueden contener letras\n"
                        + "pulsa OK e intentelo de nuevo\n";

            } else if (!listaDeVehiculos.stream().anyMatch(
                    matriculaCamion -> matriculaCamion.getMatricula().equalsIgnoreCase(matricula))) {

                textoDialogo += "La matricula proporcionada no pertenece a nuestra empresa\n";

            }
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR AL ALQUILAR CAMIÓN", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_continuarMatriculaJButtonActionPerformed

    private void continuarNumeroDeDiasJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarNumeroDeDiasJButtonActionPerformed

        String matricula = matriculaDeCamionJTextField.getText();
        String numeroDeDias = numeroDeDiasAlquilerJTextField.getText();
        String textoDialogo = "[i] Error detectado\n";

        if (!numeroDeDias.isEmpty()
                && numeroDeDias.matches("^[0-9]+$")) {
            this.listaDeVehiculos.forEach(
                    camion -> {
                        if (camion instanceof Camion) {
                            if (camion.getMatricula().equalsIgnoreCase(matricula)
                            && !camion.isAlquilado()) {

                                ((Camion) camion).setAlquilado(true);
                                ((Camion) camion).setDiasAlquilar(Integer.parseInt(numeroDeDias));
                            }
                        }
                    });

            textoDialogo = "El casmión con matricula: " + matricula 
                    +" ha sido alquilado.\n"
                    +"[i] Total Camiones: "
                    + this.listaDeVehiculos
                            .stream()
                            .filter(vehiculo -> vehiculo instanceof Camion).count()
                    + " Alquilados: " + this.listaDeVehiculos.stream()
                            .filter(vehiculo -> vehiculo instanceof Camion && vehiculo.isAlquilado())
                            .count();

            JOptionPane.showMessageDialog(this, textoDialogo, "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } else if (numeroDeDias.isEmpty()) {

            textoDialogo += "No se ha proporcionado el numero de dias de alquiler\n";
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR EN EL NUMERO", JOptionPane.ERROR_MESSAGE);

        } else if (!numeroDeDias.matches("^[0-9]+$")) {

            textoDialogo += "Solo se admiten numeros, no se permiten letras ni carácteres especiales\n";
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR EN EL NUMERO", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_continuarNumeroDeDiasJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alquilerDeCamionesJLabel;
    private javax.swing.JPanel alquilerDeCamionesJPanel;
    private javax.swing.JButton continuarMatriculaJButton;
    private javax.swing.JButton continuarNumeroDeDiasJButton;
    private javax.swing.JPanel diasDeAlquilerCamionesJPanel;
    private javax.swing.JLabel indicarMatriculaCamionJLabel;
    private javax.swing.JPanel indicarMatriculaJPanel;
    private javax.swing.JLabel indicarNumeroDeDiasJLabel;
    private javax.swing.JTextField matriculaDeCamionJTextField;
    private javax.swing.JTextField numeroDeDiasAlquilerJTextField;
    // End of variables declaration//GEN-END:variables
}
