package actividad_1_1_c.Interfaces;

import actividad_1_1_c.ClasesEInterfaces.Camion;
import actividad_1_1_c.ClasesEInterfaces.Turismo;
import actividad_1_1_c.ClasesEInterfaces.Vehiculo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AlquilerDeCoches extends javax.swing.JFrame {

    ArrayList<Vehiculo> listaDeVehiculos;

    public AlquilerDeCoches(ArrayList<Vehiculo> lista) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaDeVehiculos = lista;
        diasDeAlquilerDeCocheJPanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alquilerDeCochesJPanel = new javax.swing.JPanel();
        alquilerDeCochesJLabel = new javax.swing.JLabel();
        indicaMatriculaJPanel = new javax.swing.JPanel();
        matriculaCocheContratadoJLabel = new javax.swing.JLabel();
        matriculaCocheAlquiladoJTextFeild = new javax.swing.JTextField();
        continuarMatriculaJButton = new javax.swing.JButton();
        diasDeAlquilerDeCocheJPanel = new javax.swing.JPanel();
        indicarNumeroDeDiasDeAlquilerJLabel = new javax.swing.JLabel();
        numeroDeDiasAlquilerJTextField = new javax.swing.JTextField();
        indicarNumeroDeDiasAlquilerJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alquiler de coches");
        setMinimumSize(null);
        setResizable(false);

        alquilerDeCochesJPanel.setMaximumSize(null);
        alquilerDeCochesJPanel.setName(""); // NOI18N
        alquilerDeCochesJPanel.setPreferredSize(new java.awt.Dimension(500, 350));

        alquilerDeCochesJLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        alquilerDeCochesJLabel.setText("ALQUILER DE COCHES");

        indicaMatriculaJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        indicaMatriculaJPanel.setMaximumSize(null);
        indicaMatriculaJPanel.setName(""); // NOI18N

        matriculaCocheContratadoJLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        matriculaCocheContratadoJLabel.setText("INDICA LA MATRÍCULA DEL COCHE CONTRATADO:");

        continuarMatriculaJButton.setText("CONTINUAR");
        continuarMatriculaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarMatriculaJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indicaMatriculaJPanelLayout = new javax.swing.GroupLayout(indicaMatriculaJPanel);
        indicaMatriculaJPanel.setLayout(indicaMatriculaJPanelLayout);
        indicaMatriculaJPanelLayout.setHorizontalGroup(
            indicaMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indicaMatriculaJPanelLayout.createSequentialGroup()
                .addGroup(indicaMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indicaMatriculaJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(matriculaCocheContratadoJLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, indicaMatriculaJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(continuarMatriculaJButton)))
                .addContainerGap())
            .addGroup(indicaMatriculaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matriculaCocheAlquiladoJTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        indicaMatriculaJPanelLayout.setVerticalGroup(
            indicaMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indicaMatriculaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matriculaCocheContratadoJLabel)
                .addGap(18, 18, 18)
                .addComponent(matriculaCocheAlquiladoJTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(continuarMatriculaJButton)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        diasDeAlquilerDeCocheJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        diasDeAlquilerDeCocheJPanel.setEnabled(false);
        diasDeAlquilerDeCocheJPanel.setMaximumSize(null);
        diasDeAlquilerDeCocheJPanel.setName(""); // NOI18N
        diasDeAlquilerDeCocheJPanel.setOpaque(false);

        indicarNumeroDeDiasDeAlquilerJLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        indicarNumeroDeDiasDeAlquilerJLabel.setText("INDICAR NÚMERO DE DÍAS DE ALQUILER:");

        indicarNumeroDeDiasAlquilerJButton.setText("CONTINUAR");
        indicarNumeroDeDiasAlquilerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indicarNumeroDeDiasAlquilerJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diasDeAlquilerDeCocheJPanelLayout = new javax.swing.GroupLayout(diasDeAlquilerDeCocheJPanel);
        diasDeAlquilerDeCocheJPanel.setLayout(diasDeAlquilerDeCocheJPanelLayout);
        diasDeAlquilerDeCocheJPanelLayout.setHorizontalGroup(
            diasDeAlquilerDeCocheJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diasDeAlquilerDeCocheJPanelLayout.createSequentialGroup()
                .addGroup(diasDeAlquilerDeCocheJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diasDeAlquilerDeCocheJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(indicarNumeroDeDiasDeAlquilerJLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diasDeAlquilerDeCocheJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(indicarNumeroDeDiasAlquilerJButton)))
                .addContainerGap())
            .addGroup(diasDeAlquilerDeCocheJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeroDeDiasAlquilerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diasDeAlquilerDeCocheJPanelLayout.setVerticalGroup(
            diasDeAlquilerDeCocheJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diasDeAlquilerDeCocheJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indicarNumeroDeDiasDeAlquilerJLabel)
                .addGap(18, 18, 18)
                .addComponent(numeroDeDiasAlquilerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indicarNumeroDeDiasAlquilerJButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout alquilerDeCochesJPanelLayout = new javax.swing.GroupLayout(alquilerDeCochesJPanel);
        alquilerDeCochesJPanel.setLayout(alquilerDeCochesJPanelLayout);
        alquilerDeCochesJPanelLayout.setHorizontalGroup(
            alquilerDeCochesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alquilerDeCochesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alquilerDeCochesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alquilerDeCochesJPanelLayout.createSequentialGroup()
                        .addComponent(alquilerDeCochesJLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(diasDeAlquilerDeCocheJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indicaMatriculaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        alquilerDeCochesJPanelLayout.setVerticalGroup(
            alquilerDeCochesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alquilerDeCochesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alquilerDeCochesJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indicaMatriculaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diasDeAlquilerDeCocheJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alquilerDeCochesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alquilerDeCochesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indicarNumeroDeDiasAlquilerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indicarNumeroDeDiasAlquilerJButtonActionPerformed

        String matricula = matriculaCocheAlquiladoJTextFeild.getText();
        String numeroDeDias = numeroDeDiasAlquilerJTextField.getText();
        String textoDialogo = "[i] Error detectado\n";

        if (!numeroDeDias.isEmpty()
                && numeroDeDias.matches("^[0-9]+$")) {
            this.listaDeVehiculos.forEach(
                    turismo -> {
                        if (turismo instanceof Turismo) {
                            if (turismo.getMatricula().equalsIgnoreCase(matricula)
                            && !turismo.isAlquilado()) {

                                ((Turismo) turismo).setAlquilado(true);
                                ((Turismo) turismo).setDiasAlquilar(Integer.parseInt(numeroDeDias));
                            }
                        }
                    });

            textoDialogo = "El coche con matrícula: " + matricula 
                    +" ha sido alquilado.\n"
                    +"[i] Total Turismos: "
                    + this.listaDeVehiculos
                            .stream()
                            .filter(vehiculo -> vehiculo instanceof Turismo).count()
                    + " Alquilados: " + this.listaDeVehiculos.stream()
                            .filter(vehiculo -> vehiculo instanceof Turismo && vehiculo.isAlquilado())
                            .count();

            JOptionPane.showMessageDialog(this, textoDialogo, "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } else if (numeroDeDias.isEmpty()) {

            textoDialogo += "No se ha proporcionado el numero de días de alquiler\n";
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR EN EL NUMERO", JOptionPane.ERROR_MESSAGE);

        } else if (!numeroDeDias.matches("^[0-9]+$")) {

            textoDialogo += "Solo se admiten numeros, no se permiten letras ni caracteres especiales\n";
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR EN EL NUMERO", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_indicarNumeroDeDiasAlquilerJButtonActionPerformed

    private void continuarMatriculaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarMatriculaJButtonActionPerformed

        String matricula = matriculaCocheAlquiladoJTextFeild.getText();
        String numeroDeDias = "";
        String textoDialogo = "[i] Error detectado:\n";
        
        if (this.listaDeVehiculos.stream().anyMatch(turismo -> turismo instanceof Camion
                && turismo.getMatricula().equalsIgnoreCase(matricula))) {
            
            textoDialogo += "Esa matricula no pertenece a un turismo";
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR AL ALQUILAR TURISMO", JOptionPane.QUESTION_MESSAGE);
        
            
        }  else if (this.listaDeVehiculos.stream().anyMatch(
                turismo -> turismo instanceof Turismo 
                        && turismo.isAlquilado() 
                        && turismo.getMatricula().equalsIgnoreCase(matricula))) {

            textoDialogo += "El turismo con matricula \n" + matricula + " ya esta alquilado\n";
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR AL ALQUILAR TURISMO", JOptionPane.QUESTION_MESSAGE);

        } else if (!matricula.isEmpty()
                && this.listaDeVehiculos
                        .stream()
                        .anyMatch(
                                matriculaTurismo -> matriculaTurismo
                                        .getMatricula()
                                        .equalsIgnoreCase(matricula))) {

            matriculaCocheAlquiladoJTextFeild.setEditable(false);
            continuarMatriculaJButton.setEnabled(false);
            diasDeAlquilerDeCocheJPanel.setVisible(true);

        } else {
            if (matricula.isEmpty()) {

                textoDialogo += "No se ha proporcionado matricula\n";

            } else if (!matricula.matches("^[A-Za-z]{1,2}-[0-9]{4}-[A-Za-z]{1,3}$")) {

                textoDialogo += "La matricula no tiene el formato correcto, el formato correcto es XX-XXXX-XXX donde:\n"
                        + " - XX:   representa el pais o region de la matricula\n"
                        + " - XXXX: representa el numero de la matricula\n"
                        + " - XXX:  representa las tres ultimas letras de una matricula\n"
                        + "XX solo pueden contener letras, XXXX solo pueden contener numeros y XXX solo pueden contener letras\n"
                        + "pulsa OK e intentelo de nuevo\n";

            } else if (!listaDeVehiculos.stream().anyMatch(
                    matriculaTurismo -> matriculaTurismo.getMatricula().equalsIgnoreCase(matricula))) {

                textoDialogo += "La matricula proporcionada no pertenece a nuestra empresa\n";

            }
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR AL ALQUILAR TURISMO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_continuarMatriculaJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alquilerDeCochesJLabel;
    private javax.swing.JPanel alquilerDeCochesJPanel;
    private javax.swing.JButton continuarMatriculaJButton;
    private javax.swing.JPanel diasDeAlquilerDeCocheJPanel;
    private javax.swing.JPanel indicaMatriculaJPanel;
    private javax.swing.JButton indicarNumeroDeDiasAlquilerJButton;
    private javax.swing.JLabel indicarNumeroDeDiasDeAlquilerJLabel;
    private javax.swing.JTextField matriculaCocheAlquiladoJTextFeild;
    private javax.swing.JLabel matriculaCocheContratadoJLabel;
    private javax.swing.JTextField numeroDeDiasAlquilerJTextField;
    // End of variables declaration//GEN-END:variables
}
