package actividad_1_1_c.Interfaces;

import actividad_1_1_c.ClasesEInterfaces.Camion;
import actividad_1_1_c.ClasesEInterfaces.Turismo;
import actividad_1_1_c.ClasesEInterfaces.Vehiculo;
import java.util.ArrayList;
import java.util.Optional;
import javax.swing.JOptionPane;

public class DevolverVehiclos extends javax.swing.JFrame {

    ArrayList<Vehiculo> listaDeVehiculos;

    public DevolverVehiclos(ArrayList<Vehiculo> lista) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaDeVehiculos = lista;
        indicarElNumeroDeDiasJPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDevovlerCocheJPanel = new javax.swing.JPanel();
        devolverVehiculoJLabel = new javax.swing.JLabel();
        indicarNumeroMatriculaJPanel = new javax.swing.JPanel();
        devloveerVehiculoJLabel = new javax.swing.JLabel();
        matriculaADevolverJTextField = new javax.swing.JTextField();
        tipoDeVehiculoJTextField = new javax.swing.JTextField();
        esCorrectaLaMatriculaJButton = new javax.swing.JButton();
        indicarElNumeroDeDiasJPanel = new javax.swing.JPanel();
        numeroDeDiasJLabel = new javax.swing.JLabel();
        diasContratadosJTextField = new javax.swing.JTextField();
        diasConsumidosJTextField = new javax.swing.JTextField();
        cantidadAPagarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(null);
        setResizable(false);

        panelDevovlerCocheJPanel.setMaximumSize(null);
        panelDevovlerCocheJPanel.setName(""); // NOI18N
        panelDevovlerCocheJPanel.setPreferredSize(new java.awt.Dimension(565, 350));

        devolverVehiculoJLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        devolverVehiculoJLabel.setText("DEVOLVER VEHÍCULO");

        indicarNumeroMatriculaJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        indicarNumeroMatriculaJPanel.setPreferredSize(new java.awt.Dimension(525, 130));

        devloveerVehiculoJLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        devloveerVehiculoJLabel.setText("ÍNDICAR NÚMERO DE MATRÍCULA  DEL VEHÍCULO A DEVOLVER:");

        tipoDeVehiculoJTextField.setEditable(false);

        esCorrectaLaMatriculaJButton.setText("CONTINUAR");
        esCorrectaLaMatriculaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esCorrectaLaMatriculaJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indicarNumeroMatriculaJPanelLayout = new javax.swing.GroupLayout(indicarNumeroMatriculaJPanel);
        indicarNumeroMatriculaJPanel.setLayout(indicarNumeroMatriculaJPanelLayout);
        indicarNumeroMatriculaJPanelLayout.setHorizontalGroup(
            indicarNumeroMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indicarNumeroMatriculaJPanelLayout.createSequentialGroup()
                .addGroup(indicarNumeroMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indicarNumeroMatriculaJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(indicarNumeroMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(devloveerVehiculoJLabel)
                            .addGroup(indicarNumeroMatriculaJPanelLayout.createSequentialGroup()
                                .addComponent(matriculaADevolverJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipoDeVehiculoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(indicarNumeroMatriculaJPanelLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(esCorrectaLaMatriculaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        indicarNumeroMatriculaJPanelLayout.setVerticalGroup(
            indicarNumeroMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indicarNumeroMatriculaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(devloveerVehiculoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(indicarNumeroMatriculaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculaADevolverJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoDeVehiculoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(esCorrectaLaMatriculaJButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        indicarElNumeroDeDiasJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        numeroDeDiasJLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        numeroDeDiasJLabel.setText("ÍNDICAR EL NÚMERO DE DÍAS CON EL SERVICIO:");

        diasContratadosJTextField.setEditable(false);
        diasContratadosJTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        cantidadAPagarJButton.setText("CONTINUAR");
        cantidadAPagarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadAPagarJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indicarElNumeroDeDiasJPanelLayout = new javax.swing.GroupLayout(indicarElNumeroDeDiasJPanel);
        indicarElNumeroDeDiasJPanel.setLayout(indicarElNumeroDeDiasJPanelLayout);
        indicarElNumeroDeDiasJPanelLayout.setHorizontalGroup(
            indicarElNumeroDeDiasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indicarElNumeroDeDiasJPanelLayout.createSequentialGroup()
                .addGroup(indicarElNumeroDeDiasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indicarElNumeroDeDiasJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(indicarElNumeroDeDiasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numeroDeDiasJLabel)
                            .addGroup(indicarElNumeroDeDiasJPanelLayout.createSequentialGroup()
                                .addComponent(diasContratadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(diasConsumidosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(indicarElNumeroDeDiasJPanelLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(cantidadAPagarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        indicarElNumeroDeDiasJPanelLayout.setVerticalGroup(
            indicarElNumeroDeDiasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indicarElNumeroDeDiasJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeroDeDiasJLabel)
                .addGap(18, 18, 18)
                .addGroup(indicarElNumeroDeDiasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diasContratadosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diasConsumidosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cantidadAPagarJButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDevovlerCocheJPanelLayout = new javax.swing.GroupLayout(panelDevovlerCocheJPanel);
        panelDevovlerCocheJPanel.setLayout(panelDevovlerCocheJPanelLayout);
        panelDevovlerCocheJPanelLayout.setHorizontalGroup(
            panelDevovlerCocheJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDevovlerCocheJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDevovlerCocheJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indicarNumeroMatriculaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(panelDevovlerCocheJPanelLayout.createSequentialGroup()
                        .addComponent(devolverVehiculoJLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(indicarElNumeroDeDiasJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDevovlerCocheJPanelLayout.setVerticalGroup(
            panelDevovlerCocheJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDevovlerCocheJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(devolverVehiculoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indicarNumeroMatriculaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indicarElNumeroDeDiasJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDevovlerCocheJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDevovlerCocheJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void esCorrectaLaMatriculaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esCorrectaLaMatriculaJButtonActionPerformed

        String matricula = matriculaADevolverJTextField.getText();
        String textoDialogo = "[i] Error detectado\n";

        if (!matricula.isEmpty()
                && this.listaDeVehiculos.stream().anyMatch(vehiculo -> vehiculo.isAlquilado()
                && vehiculo.getMatricula().equalsIgnoreCase(matricula))) {

            Optional<Vehiculo> primerVehiculo = listaDeVehiculos.stream()
                    .filter(vehiculo -> vehiculo.getMatricula().equalsIgnoreCase(matricula))
                    .findFirst();

            if (primerVehiculo.isPresent()) {

                Vehiculo vehiculoEncontrado = primerVehiculo.get();

                tipoDeVehiculoJTextField.setText(vehiculoEncontrado.getClass().getSimpleName().toUpperCase());
                matriculaADevolverJTextField.setEditable(false);
                tipoDeVehiculoJTextField.setEditable(false);
                esCorrectaLaMatriculaJButton.setEnabled(false);
                indicarElNumeroDeDiasJPanel.setVisible(true);

                if (vehiculoEncontrado instanceof Turismo) {

                    Turismo nuevo = (Turismo) vehiculoEncontrado;
                    diasContratadosJTextField.setText("Días contratados: " + nuevo.getDiasAlquilar());

                } else {

                    Camion nuevo = (Camion) vehiculoEncontrado;
                    diasContratadosJTextField.setText("Días contratados: " + nuevo.getDiasAlquilar());

                }

            }

        } else {
            if (matricula.isEmpty()) {

                textoDialogo += "No se ha proporcionado matrícula\n";

            } else if (!matricula.matches("^[A-Za-z]{1,2}-[0-9]{4}-[A-Za-z]{1,3}$")) {

                textoDialogo += "La matrícula no tiene el formato correcto, el formato correcto es XX-XXXX-XXX donde:\n"
                        + " - XX:   representa el país o región de la matrícula\n"
                        + " - XXXX: representa el número de la matrícula\n"
                        + " - XXX:  representa las tres últimas letras de una matrícula\n"
                        + "XX solo pueden contener letras, XXXX solo pueden contener n´meros y XXX solo pueden contener letras\n"
                        + "pulsa OK e inténtelo de nuevo\n";

            } else if (!listaDeVehiculos.stream().anyMatch(
                    matriculaTurismo -> matriculaTurismo.getMatricula().equalsIgnoreCase(matricula))) {

                textoDialogo += "La matrícula proporcionada no pertenece a nuestra empresa\n";

            } else if (this.listaDeVehiculos.stream().anyMatch(vehiculo -> !vehiculo.isAlquilado()
                    && vehiculo.getMatricula().equalsIgnoreCase(matricula))) {

                textoDialogo += "Ese vehículo no se encuentra alquilado\n";
            }
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR AL DEVOLVER VEHÍCULO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_esCorrectaLaMatriculaJButtonActionPerformed

    private void cantidadAPagarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadAPagarJButtonActionPerformed

        String matricula = matriculaADevolverJTextField.getText();
        String textoDialogo = "[i] Error detectado\n";
        StringBuilder textoDialogoBuilder = new StringBuilder();
        String numeroDeDias = "";

        if (!diasConsumidosJTextField.getText().isEmpty()
                && diasConsumidosJTextField.getText().matches("^[0-9]+$")) {
            this.listaDeVehiculos.forEach(
                    vehiculo -> {

                        if (vehiculo.getMatricula().equalsIgnoreCase(matricula)) {

                            if (vehiculo instanceof Turismo && vehiculo.getMatricula().equalsIgnoreCase(matricula)) {
                                vehiculo.setAlquilado(false);
                                ((Turismo) vehiculo).setDiasDevolucion(Integer.parseInt(diasConsumidosJTextField.getText()));
                                textoDialogoBuilder.append(vehiculo.mostarInformacion());
                            } else if (vehiculo instanceof Camion && vehiculo.getMatricula().equalsIgnoreCase(matricula)) {
                                vehiculo.setAlquilado(false);
                                ((Camion) vehiculo).setDiasDevolucion(Integer.parseInt(diasConsumidosJTextField.getText()));
                                textoDialogoBuilder.append(vehiculo.mostarInformacion());
                            }
                        }
                    });

            textoDialogo = textoDialogoBuilder.toString();

            JOptionPane.showMessageDialog(this, textoDialogo, "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } else if (numeroDeDias.isEmpty()) {

            textoDialogo += "No se ha proporcionado el numero de dias de alquiler\n";
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR EN EL NUMERO", JOptionPane.ERROR_MESSAGE);

        } else if (!numeroDeDias.matches("^[0-9]+$")) {

            textoDialogo += "Solo se admiten números, no se permiten letras ni caracteres especiales\n";
            JOptionPane.showMessageDialog(null, textoDialogo, "ERROR EN EL NUMERO", JOptionPane.ERROR_MESSAGE);

        }

        this.dispose();

    }//GEN-LAST:event_cantidadAPagarJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cantidadAPagarJButton;
    private javax.swing.JLabel devloveerVehiculoJLabel;
    private javax.swing.JLabel devolverVehiculoJLabel;
    private javax.swing.JTextField diasConsumidosJTextField;
    private javax.swing.JTextField diasContratadosJTextField;
    private javax.swing.JButton esCorrectaLaMatriculaJButton;
    private javax.swing.JPanel indicarElNumeroDeDiasJPanel;
    private javax.swing.JPanel indicarNumeroMatriculaJPanel;
    private javax.swing.JTextField matriculaADevolverJTextField;
    private javax.swing.JLabel numeroDeDiasJLabel;
    private javax.swing.JPanel panelDevovlerCocheJPanel;
    private javax.swing.JTextField tipoDeVehiculoJTextField;
    // End of variables declaration//GEN-END:variables
}
