package actividad_1_1_c.Interfaces;

import actividad_1_1_c.ClasesEInterfaces.Listar;
import actividad_1_1_c.ClasesEInterfaces.Vehiculo;
import java.util.ArrayList;

public class VentanaListar extends javax.swing.JFrame {

    ArrayList <Vehiculo> listaDeVehiculos;
    
    public VentanaListar(ArrayList <Vehiculo> lista) {
        initComponents();
        this.listaDeVehiculos = lista;
       
        Listar resumen = new Listar();
        
        listaDeVehiculos.forEach(vehiculo -> listadoDeVehiculosJTextArea.append(vehiculo.toString() + "\n-----------------\n"));
        listadoDeVehiculosJTextArea.append("\n\n\n\n");
        listadoDeVehiculosJTextArea.append(resumen.mostrar(this.listaDeVehiculos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaListadoJPanel = new javax.swing.JPanel();
        listadoVehiculosJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoDeVehiculosJTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de vehículos");
        setMinimumSize(null);
        setResizable(false);

        ventanaListadoJPanel.setMaximumSize(null);
        ventanaListadoJPanel.setPreferredSize(new java.awt.Dimension(350, 600));

        listadoVehiculosJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listadoVehiculosJLabel.setText("LISTADO:");
        listadoVehiculosJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listadoVehiculosJLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jScrollPane1.setMaximumSize(null);
        jScrollPane1.setMinimumSize(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(305, 400));

        listadoDeVehiculosJTextArea.setEditable(false);
        listadoDeVehiculosJTextArea.setColumns(20);
        listadoDeVehiculosJTextArea.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        listadoDeVehiculosJTextArea.setRows(5);
        listadoDeVehiculosJTextArea.setMaximumSize(null);
        listadoDeVehiculosJTextArea.setName(""); // NOI18N
        jScrollPane1.setViewportView(listadoDeVehiculosJTextArea);

        javax.swing.GroupLayout ventanaListadoJPanelLayout = new javax.swing.GroupLayout(ventanaListadoJPanel);
        ventanaListadoJPanel.setLayout(ventanaListadoJPanelLayout);
        ventanaListadoJPanelLayout.setHorizontalGroup(
            ventanaListadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaListadoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaListadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaListadoJPanelLayout.createSequentialGroup()
                        .addComponent(listadoVehiculosJLabel)
                        .addGap(0, 273, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ventanaListadoJPanelLayout.setVerticalGroup(
            ventanaListadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaListadoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listadoVehiculosJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaListadoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaListadoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listadoDeVehiculosJTextArea;
    private javax.swing.JLabel listadoVehiculosJLabel;
    private javax.swing.JPanel ventanaListadoJPanel;
    // End of variables declaration//GEN-END:variables
}
